### ISSUE TITLE
Add support to detect internal hard disk and install to it.

### ISSUE THREAD

**Issue by kalyankondapally** [android-ia/bootable-live-installer#2]
As discussed offline, some times installer direct detect internal hd correctly but only usb. This issue is to fix this.

**Comment by tpalli** [comment]
there seems to be still problems with Joule board, it errors out on some command like "ls /dev/sd*", I'm running android-ia from sd and trying to install to mmcblk0

**Comment by kalyankondapally** [comment]
@shobhitka ping

**Comment by shobhitka** [comment]
@tpalli , can you test again with latest code. I am not sure if you are using the latest code. The command you mentioned to fail was used earlier but now we use extended regular expression to support  all possible devices like - ls /dev/[hms][dm][0-9a-z]*

In case I am wrong and you have indeed used latest code, can you give me full dump of the logs that are there ?

**Comment by kalyankondapally** [comment]
@tpalli  Does this issue exist.

**Comment by kalyankondapally** [comment]
@shobhitka @cmsanta also saw mmc related error in logcat.

**Comment by cmsanta** [comment]
The issue on logcat that I saw looks like this:

11-14 04:19:17.341  2307  2800 W StorageManager: Could not read /sys/block/mmcblk0/size
11-14 04:19:17.341  2307  2800 W StorageManager: java.io.FileNotFoundException: /sys/block/mmcblk0/size (No such file or directory)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at java.io.FileInputStream.open(Native Method)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at java.io.FileInputStream.<init>(FileInputStream.java:99)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at android.os.storage.StorageManager.readLong(StorageManager.java:944)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at android.os.storage.StorageManager.getPrimaryStorageSize(StorageManager.java:935)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at com.android.settings.deviceinfo.StorageSettings$SummaryProvider.updateSummary(StorageSettings.java:492)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at com.android.settings.deviceinfo.StorageSettings$SummaryProvider.setListening(StorageSettings.java:484)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at com.android.settings.dashboard.SummaryLoader.setListeningW(SummaryLoader.java:192)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at com.android.settings.dashboard.SummaryLoader.-wrap2(SummaryLoader.java)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at com.android.settings.dashboard.SummaryLoader$Worker.handleMessage(SummaryLoader.java:253)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at android.os.Looper.loop(Looper.java:154)
11-14 04:19:17.341  2307  2800 W StorageManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
